CREATE TABLE Log_Objetos 
(cod_Log VARCHAR2(20) 
NOT NULL PRIMARY KEY,
descripcion VARCHAR2(50) NOT NULL,
fecha VARCHAR2(30) NULL,
usuario VARCHAR2(10) NULL,
cargo VARCHAR2(30) NULL);

create or replace TRIGGER Todos_objetos1
BEFORE INSERT OR DELETE OR UPDATE ON PRODUCTOS
FOR EACH ROW
DECLARE
V_USERNAME VARCHAR2(30);
V_FECHA DATE;
BEGIN
SELECT USER INTO V_USERNAME from dual;
SELECT SYSDATE INTO V_FECHA from dual;

IF INSERTING THEN
INSERT INTO LOG_OBJETOS(cod_Log,descripcion,fecha,usuario,cargo) VALUES('I-'||:NEW.CODIGOPRODUCTO,'RI'||:NEW.NOMBRE,V_FECHA,V_USERNAME,'Contador');
END IF;

IF DELETING THEN
INSERT INTO LOG_OBJETOS(cod_Log,descripcion,fecha,usuario,cargo) VALUES('D-'||:OLD.CODIGOPRODUCTO,'RD'||:OLD.NOMBRE,V_FECHA,V_USERNAME,'Contador');
END IF;

IF UPDATING THEN

INSERT INTO LOG_OBJETOS(cod_Log,descripcion,fecha,usuario,cargo) VALUES('U-'||:NEW.CODIGOPRODUCTO,'RU'||:NEW.NOMBRE,V_FECHA,V_USERNAME,'Contador');

END IF;
END Todos_objetos1;

UPDATE PRODUCTOS SET GAMA='Herramientas'  WHERE CODIGOPRODUCTO='11679';

INSERT INTO PRODUCTOS(CODIGOPRODUCTO,NOMBRE,GAMA,DIMENSIONES,PROVEEDOR,DESCRIPCION,CANTIDADENSTOCK,PRECIOVENTA,PRECIOPROVEEDOR) VALUES('500','Televisor100','Frutales','56','Otro','','15','30000','10000');

DELETE FROM PRODUCTOS WHERE CODIGOPRODUCTO ='500';